# Generated by Django 2.1.3 on 2018-11-06 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Perrito',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fotografia', models.ImageField(upload_to='')),
                ('nombre', models.CharField(max_length=30)),
                ('raza_predominante', models.CharField(max_length=50)),
                ('descripcion', models.TextField(max_length=100)),
                ('estado', models.CharField(choices=[('Rescatado', 'Rescatado'), ('Disponible', 'Disponible'), ('Adoptado', 'Adoptado')], max_length=15)),
            ],
        ),
    ]
